server.port=${PORT:5000}

# MySQL Data Source Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Gemini API Key Configuration
gemini.api.key=${GEMINI_API_KEY:}

# Logger Settings
logging.level.org.springframework.web=INFO
logging.level.com.workspace.apiserver=DEBUG
logging.level.org.springframework.security=DEBUG

